# Builds and uploads jar

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create release dir
      run: mkdir release

    - name: Add postaCA config
      run: cp ./pkcs11-posta.cfg release/

    - name: Add jar to release
      run: cp target/PaxyPDFSigner-*.jar release/PaxyPDFSigner.jar

    - name: zip release
      run: zip -r release.zip release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        name: PaxyPdfSigner.zip
        path: release.zip

